dataset:
  train_csv_path: dataset/data/train.csv
  test_csv_path: dataset/data/test.csv
  val_csv_path: dataset/data/val.csv
  batch_size: 4
  num_workers: 0
  resolution: 224
  train_val_split: 0.8
  max_seq_length: 2048
  pin_memory: true
  shuffle: true
  utilize_memory: false
  file_index: 0
  use_paligemma: true

model:
  model_id: '/home/vicks/.cache/kagglehub/models/victorumesiobi/physionet/transformers/1/1'
  use_lora: false
  use_qlora: false
  freeze_vision: true
  num_epochs: 1
  eval_steps: 100
  save_steps: 100
  save_total_limit: 1
  logging_steps: 20
  logging_dir: './checkpoints/logs'
  evaluation_strategy: 'steps'
  output_dir: './checkpoints'
  fp16: true
  push_to_hub: false
  resume_from_checkpoint: /home/featurize/work/physionet/ai/checkpoints/paligemma-epoch=0-val_loss=6.00.ckpt